name: CI/CD Workflow

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  build-and-test-dev:
    name: Build, Test, and Deploy in Development
    runs-on: ubuntu-latest
    environment: Service1-dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Service1 Development
      run: echo "This for Service1 Development"

    - name: Build
      run: |
        echo "Building the project in Development environment..."

    - name: Test
      run: |
        echo "Running tests in Development environment..."

    - name: Deploy
      run: |
        echo "Deploying to Development environment..."
       

  build-and-test-prod:
    name: Build, Test, and Deploy in Production
    runs-on: ubuntu-latest
    needs: build-and-test-dev
    environment: service1-prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Service2 Development
      run: echo "This for Service2 Development"

    - name: Build
      run: |
        echo "Building the project in Production environment..."

    - name: Test
      run: |
        echo "Running tests in Production environment..."
       
    - name: Deploy
      run: |
        echo "Deploying to Production environment..."
